services:

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ecommerce-db
    restart: unless-stopped

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Ecommerce_Pass1!"
      MSSQL_PID: "Developer"

    volumes:
      - mssqldata:/var/opt/mssql

    ports:
      - "14330:1433"

  db-init:
    build:
      context: ./db
      dockerfile: Dockerfile

    container_name: ecommerce-db-init

    depends_on:
      - db

    environment:
      MSSQL_SA_PASSWORD: "Ecommerce_Pass1!"

    volumes:
      - ./db/migrations:/migrations:ro

    restart: "no"

  app:
    build: .
    container_name: ecommerce-app
    restart: unless-stopped

    depends_on:
      db-init:
        condition: service_completed_successfully

    environment:
      DB_URL: "jdbc:sqlserver://db:1433;databaseName=ecommerce_db;encrypt=true;trustServerCertificate=true"
      DB_USER: "sa"
      DB_PASSWORD: "Ecommerce_Pass1!"

    ports:
      - "8080:8080"


volumes:
  mssqldata:
